version: '3.8'

services:
  backend:
    build: ./backend/predictor
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend/image-uploader
    ports:
      - "3001:3001"
#    depends_on:
#      - backend
